택배 송장 제조기 [STEP 1] jacob
yagom-academy/refectoring-parcel-invoice pull request #1
Opened 2024-01-22 11:27 UTC by wargi

### 조언을 얻고 싶은 부분
- 객체미용체조 7원칙 ‘2개 이상의 원시타입 프로퍼티를 갖는 타입 금지’이 계산 속성까지 포함해야 하는지 궁금합니다!

2024-01-22 12:15 UTC, yagom commented
@wargi 캠핑사이트에서 `Pull Request 보낼 때 꼭 확인하세요!` 내용을 확인해주세요. 이렇게 보내시면 리뷰어가 확인을 할 수 없습니다.
리뷰어를 태그해주셔야해요.
리뷰어를 태그하지 않으시면 리뷰가 늦어집니다.
이번엔 제가 대신 태그해드려요!
@zdodev

2024-01-23 13:56 UTC, zdodev requested changes
안녕하세요. @wargi !
리뷰어 소대입니다!

스텝1 구현을 상당히 빨리 진행해주셨네요👍
요구사항에 따라 깔끔하게 개선해보신 점이 좋았습니다!

적어주신 질문의 내용과 함께 여러 코멘트를 작성해보았습니다.
같이 의견 나눠보면 좋을 것 같습니다!😁

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +    init(parcelProcessor: ParcelProcessing) {
`ParcelOrderViewController`에서도 DIP를 적용해보셨네요👍

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +}
`ParcelInformation`에 대한 원시값을 벌써 포장해보셨네요👍
원시값을 포장한 타입이나 이후 새로 생성한 타입에 대해서 파일을 새로 생성하거나 그룹을 생성하는 것은 어떨까요? 의견이 궁금합니다!

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    }
원시값 생성에 대한 조건을 추가해보셨네요👍

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
>  class ParcelInformation {
`ParcelInformation` 타입을 클래스로 선언하신 이유가 궁금합니다!

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    let deliveryCost: Cost
원시값 포장과 객체지향 7원칙을 지키도록 개선해보셨네요👍

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    var discountedCost: Cost {
`계산 속성`의 경우 값을 저장하여 가지고 있기 보다는 메서드와 유사한 방식으로 계산하는 프로퍼티로 객체지향 원칙의 인스턴스 변수에서 예외로 두는 것이 어떨까 생각이 듭니다. 
다른 의견이 있다면 추가로 코멘트 달아보면 좋을 것 같습니다!😁

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +         discount: Discount) throws {
`init` 인자로 지금처럼 원시값을 받는 것과, 포장된 타입으로 받는 것이 있을 수 있을 것 같습니다. 지금과 같은 방식을 선호하는지 궁금합니다!

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
>  }
데이터베이스 저장 역할을 분리해보셨네요👍

2024-01-23 13:56 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    let persistence: ParcelInformationPersistence
`private` 수준으로 선언하는 것은 어떨까요?

2024-01-23 14:30 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +         discount: Discount) throws {
앗 현재는 송장생성 이외에 개별적으로 포장된 타입을 받는 곳이 없어서 내부에서 생성되게 설정하였는데요~
포장된 타입이 개별적으로 생성되어야한다면 `init`을 포장된 타입으로 받았을 것 같습니다!

2024-01-23 14:33 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +}
https://github.com/yagom-academy/refactoring-parcel-invoice/pull/5 앗 답변 주실줄 모르고,
다음 PR을 올렸는데요! 현재 파일을 분리하긴 하였는데, 마침 요 부분에 대해서 고민이되어서 PR에 고민내용으로 작성하였는데,
소대 편하실 때 코멘트 주시면 감사하겠습니다~‼️

2024-01-23 14:34 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
>  class ParcelInformation {
처음 기본으로 선언되어 있어서 사용하였는데요!
https://github.com/yagom-academy/refactoring-parcel-invoice/pull/5 STEP2 진행하며 리팩토링하면서 수정하였는데,
확인해주시면 감사하겠습니다!😃

2024-01-23 14:36 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    let persistence: ParcelInformationPersistence
https://github.com/yagom-academy/refactoring-parcel-invoice/pull/5 요 부분도 STEP2 진행하며 같이 수정하였습니다~!
너무 성급히 올려나싶었는데,,! 빠르게 피드백주셔서 감사해요 소대 👍👍👍

2024-01-24 12:40 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +         discount: Discount) throws {
저도 같은 생각이었습니다👍

2024-01-24 14:17 UTC, zdodev approved these changes
안녕하세요. @wargi !

Step1 진행하시느라 고생하셨습니다!
질문과 남긴 코멘트는 다음 스텝에서 진행해도 될 것 같아
여기서 마무리 하도록 하겠습니다!👍

2024-01-24 14:17 UTC, merged