택배송장앱 [STEP 2] Beepeach
yagom-academy/refectoring-parcel-invoice pull request #23
Opened 2024-01-25 20:02 UTC by Beepeach

@YebinKim

븨븨! 늦은 시간에 또 멘션드려서 죄송해요!

## 고민했던 점
### Strategy 패턴
- `Discount` 열거형에 strategy 프로퍼티가 추가되는 이유는 이 프로퍼티가 없다면 `ParcelOrderView`에서 `discountStrategy`를 주입할때 swift, if 문이 추가되어야해서 들어간거라고 이해했습니다. 알맞게 이해 했을까요?
- `Discount` 열거형들어가는 switch 문은 없앨 수 없다고 생각하는데... 혹시 방법이 있나용? `Discount`는 어차피 case가 추가되면 코드 수정이 있어야하고 그에 맞춰서 switch에 case도 들어갈 수 밖에 없다고 생각해요!

### 매직넘버
```
struct VIPDiscount: DiscountStrategy {
    func applyDiscount(deliveryCost: DeliveryCost) -> DeliveryCost {
        return (try? .init(deliveryCost.value / 5 * 4)) ?? deliveryCost
    }
}
```
- 이미 만들어진거라서 따로 수정을 안했는데 요런것도 매직넘버로 보고 빼서 적어두는게 좋은건가? 할인율이니까 그냥 나둘까? 라는 생각이 들었습니다.
---

## ETC
- 보너스로 수정하고 싶은 부분이 있는데 시간 관계상 작업을 못했네요🥲 혹시 Week2할때 고쳐서 올려도 괜찮을까용?

2024-01-28 13:05 UTC, YebinKim requested changes
BeePeach 안녕하세요~
Step1에 이어 Step2 에서 바로 뵙습니다 😄

Step1에서도 Step2에서도 커밋에 작업 종류를 작성하고 수정한 내용을 상세하게 작성하는 것은 좋은 히스토리 관리 습관이라는 생각이 들어요 👍👍

---

`Discount` 열거형에 strategy 프로퍼티가 추가되는 이유와 관련해서는, 생각하신 바와 같이 `Discount` 열거형과 관련해 수정이 발생했을 때 `ParcelOrderView` 에 가는 영향을 없앰으로써 OCP를 준수하기 위함이라고 생각합니다.
다만, `ParcelOrderView` 가 `DiscountStrategy` 타입을 직접 알고 있어야 하는지는 의문이 들어 코멘트 남겨두었습니다~

그리고 `Discount` 열거형 안에 포함된 switch 구문을 없애고자 하는 이유가 무엇인지 궁금합니다!

매직넘버와 관련해서는 `5 * 4` 와 같은 할인율이 매직넘버로써 충분히 분리가 가능하다는 생각이 들어요 👍 
앞으로 `Discount` 의 case 가 늘어났을 때 코드에서 수정이 발생하는 부분을 쉽게 찾고 수정이 적게 일어날 수 있는 방향으로 설계된다면 휴먼에러를 줄이고 OCP를 잘 지킬 수 있다고 생각합니다!

---

Step1 과 더불어 Step2 까지 진행하느라 고생 많으셨습니다 😊

P2 코멘트가 있어 Request Changes 로 요청드렸지만 프로젝트 수행 기간이 지났기 때문에 해당 PR은 클로즈하고 바로 Week2 프로젝트를 진행하셔도 괜찮습니다!
혹시 추가로 해당 프로젝트에서 수정을 진행하신다면 보너스로 수정하고 싶으신 부분도 포함해서 적용해주시면 함께 의견 드릴 수 있으니 이대로 Week1 프로젝트를 수정할지 바로 Week2 를 진행할지 의견 부탁드려요~

또한, 코멘트 내용 중 궁금한 점이 있다면 언제든 질문 부탁드립니다~! 🙌

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Controllers/ParcelOrderViewController.swift
> +    init(parcelProcessor: ParcelOrderProcessing) {
프로토콜을 선언하고 주입함으로써 DIP 를 적용하셨군요!! 👍👍

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468824973)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/CostInfomation.swift
> +    let deliveryCost: DeliveryCost
p3;

`deliveryCost` 도 외부에서 접근하지 않는 프로퍼티로 보이는데 private 처리를 하지 않은 이유가 있을까요? 👀

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468823571)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/DiscountStrategy.swift
> +        return (try? .init(deliveryCost.value / 5 * 4)) ?? deliveryCost
p2;

`discountedCost` 를 사용할 때 `DeliveryCost` 의 생성에 문제가 있음에도 `deliveryCost` 가 반환되고 있어 문제를 컴파일러 단계에서 인지하기가 어려워보여요 🤔 (앱 자체는 문제없이 실행되다보니 오류가 발견되기 어려워보여요)

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468824231)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/PhoneNumber.swift
> +        guard  value.range(of: koreanPhoneNumberRegex, options: .regularExpression) != nil else { throw NSError() }
```suggestion
        guard value.range(of: koreanNameRegex, options: .regularExpression) != nil else { throw NSError() }
```

p5;

띄어쓰기가 2개 들어간 것으로 보여요 👀

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468789494)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ReceiverInfomation.swift
> +    var receiverMobile: PhoneNumber
p3;

객체의 이름과 프로퍼티에 `Receiver` 네이밍이 중복되어 사용된 것으로 보여요 👀
`ReceiverInfomation` 객체의 프로퍼티라는 것 만으로 `Receiver` 와 관련된 정보라는 것을 알릴 수 있으니 간결하게 네이밍을 해보면 어떨까요?

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468789073)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Views/ParcelOrderView.swift
> +        guard let name: Name = try? Name(receiverNameField.text ?? ""),
고민하셨던 부분과 같이 에러 타입을 정의하지 않고 try? 형태로만 핸들링한다면 `init?` 처리를 하는 것과 지금의 형태가 크게 다르지 않다고 생각돼요 🤔
또한 `receiverNameField.text` 가 nil 일 때 기본 값으로 `""`을 전달하고 있다보니 해당 라인에서 오류가 발생할 경우 `receiverNameField`로부터 값이 전달되지 않아서 Name 생성에 실패한 것인지 `Name`의 이니셜라이저에서 생성에 실패한 것인지 구분하기가 어려운 문제가 있어보입니다.

이 경우 `init?` 으로 처리하는 게 좋을지 에러 핸들링을 하는 게 좋을지 고민해보자면, 저는 `Name`이 Optional 로 존재하는 것은 무의미하다는 생각이 들어서 실패 가능한 이니셜라이저를 가지기보다는 에러 핸들링을 해주는 것이 필요하다는 생각이 들어요.
요구사항과 객체의 특성을 고려했을 때 `Name`이 Optional 로 생성된 경우 유즈케이스를 완료할 수 없기 때문에 빠르게 에러의 종류를 전달하고 이를 복구하기 위한 에러 핸들링이 적절하지 않을까 합니다 😄

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468823143)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ParcelOrderProcessing.swift
> +class ParcelOrderProcessor: ParcelOrderProcessing {
p4;

접근제한자를 꼼꼼히 적용하신 부분이 눈에 띄네요! 🤩
상속 가능성이 없는 클래스도 `final` 키워드를 적용함으로써 컴파일 성능 향상의 효과를 누려보면 어떨까요?

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468790244)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ParcelInformationPersistence.swift
> +protocol ParcelInformationPersistence {
p3;

[Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage) 에서는 protocol 네이밍을 할 때 특정 개체를 묘사할 때는 명사형의 이름을, 기능을 설명할 때는 -able, -ing 와 같은 접미사를 붙이는 것을 권장하고 있어요.
`ParcelOrderProcessing` 과 같이 해당 가이드라인을 준수한 네이밍을 사용해보면 어떨까요?

> - Protocols that describe what something is should read as nouns (e.g. Collection).
> - Protocols that describe a capability should be named using the suffixes able, ible, or ing (e.g. Equatable, ProgressReporting).

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468790101)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ParcelInformation.swift
> +    let costInfomation: CostInfomation
p4;

`Information` 이 중복되는 네이밍이라는 생각이 듭니다 🤔
프로퍼티 이름에서는 `Information` 이 빠져도 의미 전달에 문제가 없을 거 같다는 생각이 드는데 어떻게 생각하실까요?

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468825317)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/Name.swift
> +        let koreanNameRegex: String = "^[\(KoreanNameRules.firstKoreanUnicode)-\(KoreanNameRules.lastKoreanUnicode)]{\(KoreanNameRules.minNameCount),\(KoreanNameRules.maxNameCount)}$"
정규표현식을 사용해 조건을 꼼꼼하게 검증하셨군요! 👍👍

cc. [Step1](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/22/files#r1468790506)

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/DiscountStrategy.swift
> +protocol DiscountStrategy {
구체 타입에 따라 동작이 달라질 수 있도록 전략 디자인 패턴을 잘 설계하셨군요!! 🤩👍

2024-01-28 13:05 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/CostInfomation.swift
> +    init(deliveryCost: DeliveryCost, discountStrategy: DiscountStrategy) {
p2;

`DiscountStrategy` 를 주입받아야 할 필요가 있을까요? 🤔
`DiscountStrategy` 는 `Discount` 정보에 따라 결정되기 때문에 View 와 직접적인 연관을 가지지 않을 수 있는 타입이라는 생각이 들어요.

2024-01-30 09:20 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/CostInfomation.swift
> +    let deliveryCost: DeliveryCost
깜빡하고 처리를 안해줬네용!😂

2024-01-30 10:04 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/CostInfomation.swift
> +    init(deliveryCost: DeliveryCost, discountStrategy: DiscountStrategy) {
`CostInfomation`의 프로퍼티인 `discount`를 `discountStrategy`로 변경하면서 생각없이 의존성 주입 코드도 변경해줬네요.
`DiscountStrategy `대신 `Discount `를 주입하도록 변경했습니다!

2024-01-31 15:00 UTC, Beepeach reviewed
에러처리라던지 객체 미용등등 더 수정하고 싶은게 많았지만 시간상 일단 요기까지밖에 못했네요ㅠㅠ
리뷰해주서 정말 감사합니당🙏

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Views/ParcelOrderView.swift
> +        guard let name: Name = try? Name(receiverNameField.text ?? ""),
그렇군용!  
`init?`으로 할지 에러처리를 할 지에 대해서 아리송 했는데 어떤 방식으로 처리할 지 생각해보게 된 거 같아요!
조언 감사합니다👍

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/DiscountStrategy.swift
> +        return (try? .init(deliveryCost.value / 5 * 4)) ?? deliveryCost
해당 부분 말씀하신게 `DeliveryCost`가 음수일 경우 생성에 문제가 있을 수 있는데 `??`연산자로 실패했을때 또 deliveryCost가 리턴되도록 한 부분이 문제를 일으킬 소지가 있지만 이를 컴파일 단계에서 알아차리기 힘들다는 말씀이실까요?

저는 만약 에러처리 구현을 했다면  해당 부분에 문제가 발생했을때 다시 입력을 하게 하던지 하는 식으로 처리를 하면 문제가 사라질거라고 생각했습니다! 
(시간상 에러처리 부분을 구현하지 못해서 많이 아쉽습니다🥲)

혹시 잘못이해했다면 언제든 코멘트 부탁드립니당!

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/PhoneNumber.swift
> +        guard  value.range(of: koreanPhoneNumberRegex, options: .regularExpression) != nil else { throw NSError() }
앗... 감사합니다!

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ReceiverInfomation.swift
> +    var receiverMobile: PhoneNumber
말씀해주신대로 Receiver라는 의미가 중복되는거 같아서 삭제했습니다!

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ParcelOrderProcessing.swift
> +class ParcelOrderProcessor: ParcelOrderProcessing {
Week2에서 배운 내용을 토대로 적용시켜보겠습니다!

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ParcelInformationPersistence.swift
> +protocol ParcelInformationPersistence {
헛... 해당 부분을 잊고 있었는데 감사합니당!

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/ParcelInformation.swift
> +    let costInfomation: CostInfomation
말씀해주신대로 어차피 해당 프로퍼티가 Infomation이라는 의미를 담고 있는거 같아 중복된다고 생각되어 삭제했습니다!

2024-01-31 15:00 UTC, Beepeach commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/Name.swift
> +        let koreanNameRegex: String = "^[\(KoreanNameRules.firstKoreanUnicode)-\(KoreanNameRules.lastKoreanUnicode)]{\(KoreanNameRules.minNameCount),\(KoreanNameRules.maxNameCount)}$"
한글 이름만 처리했는데 하지만 만약 영어 등등 다른 언어 까지 처리하려고한다면 생각을 많이 해봐야겠어요😭

2024-02-01 09:17 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Models/DiscountStrategy.swift
> +        return (try? .init(deliveryCost.value / 5 * 4)) ?? deliveryCost
이해하신 내용이 맞습니다! 에러처리를 통해서도 해당 부분에 대한 문제를 없애줄 수 있을 거 같아요~

2024-02-01 09:19 UTC, YebinKim commented
코멘트 확인 감사합니다~
그럼 이번 프로젝트는 여기서 클로즈하고 다음 프로젝트 진행에 또 힘내보아요!! 💪🔥
고생 많으셨습니다 🙌

2024-02-01 09:21 UTC, YebinKim approved these changes

2024-02-01 09:21 UTC, merged