택배송장앱 [STEP 2] Khan1201
yagom-academy/refectoring-parcel-invoice pull request #28
Opened 2024-01-26 09:26 UTC by Khan1201

@YebinKim 
안녕하세요 븨븨 !!
1주차 내용을 이해하고 정리하느라 시간이 너무 오래 걸렸습니다 ..
늦게 PR 요청해서 너무 죄송합니다 .. 😂
<br>

## 고민했던 점
### OCP,  객체 미용 체조 2원칙 적용
주석으로 step2 요구사항 만족 코드, step2 요구사항 만족 코드를 보완한 코드로 구분하여 작성하였습니다 !

OCP(Open Close Principle) - 개방 폐쇄 원칙은 확장에는 열려있고 변경에는 닫혀있어야 합니다. 확장은 클래스의 행동의 변화 없이 가능해야 합니다. 기존 할인된 배송 가격 연산 프로퍼티에서 Discount 종류가 추가된다면 수정이 발생하므로 OCP에 위배됩니다. DiscountStrategy 프로토콜을 정의하여 연산 프로퍼티의 Discount에 따른 동작들을 추상화합니다. Discount case별로 새로운 타입을 생성 후 DiscountStrategy 프로토콜을 채택하여 함수를 정의하였습니다. 기존 요구사항에 따라서, Discount enum에 DiscountStrategy 타입의 연산 프로퍼티를 생성 후 할인된 배송 가격 연산 프로퍼티를 DiscountStrategy 타입의 함수로 접근하도록 수정하였습니다.

이렇게 추상화를 진행하여 확장에 효율적인 코드를 작성하였지만, 여전히 switch를 사용하고 있으므로 새로운 할인 종류가 생기면 Discount의 DiscountStrategy 타입의 연산 프로퍼티의 수정이 발생합니다. switch 문을 제거하고자, DiscountStrategy 프로토콜에 Discount 타입을 가지는 변수 discountCategory, 할인 적용 가능한지 Bool을 리턴하는 함수 canDiscount(category:)를 추가하였습니다. 그 후 Cost 구조체에 [DiscountStrategy] 타입의 discountStrategies을 추가하여 Discount에 해당되는 DiscountStrategy로 필터링 후 적용하였습니다 !
<br>

## 조언을 얻고 싶은 부분
### OCP,  객체 미용 체조 2원칙 적용
- 기존 요구사항 코드에서 switch문을 제거하고 싶다는 생각이 들었습니다. 제가 수정한 코드가 잘 제거가 되었는지 비비님의 의견이 궁금합니다 ! 
그리고 비비님은 switch문을 약간의 타협으로 사용을 하시는지, 아니면 아예 사용을 안하시는지 궁금합니다! 🤔
- OCP의 '확장에는 열려있고, 수정에는 닫혀있다' 라는 의미에서 '수정에는 닫혀있다'라는 부분이 아직 알쏭달쏭합니다. 어떤 enum의 case가 추가되면 기존의 해당 enum을 사용하는 코드에선 수정이 일어나면 안된다라는 말인가요? 🤔

2024-01-28 13:53 UTC, YebinKim requested changes
칸 안녕하세요! 😄

이번에도 고민하신 점들을 꼼꼼히 남겨주신 덕분에 `discountStrategies` 를 생성하신 이유와 `canDiscount(category:)` 메서드를 활용하신 이유를 이해할 수 있었어요.
다만, 이 방법이 OCP를 잘 준수하며 적용된 방법인지는 의문이 들어 코멘트 남겨두었습니다!

또한, 조언을 얻고 싶으신 부분에 대해 의견을 덧붙여보자면
저는 평소 습관으로는 enum 과 switch 조합을 즐겨 사용하는 편이지만 이번 프로젝트를 통해 OCP의 중요성을 다시 깨닫고 좀 더 프로토콜을 잘 활용해야 겠다는 생각을 했습니다 😅
OCP의 **확장에는 열려있고, 수정에는 닫혀있다** 라는 의미는 요구사항의 변경이 발생했을 때 가능하면 기존 코드에서 수정을 만들기보다는 코드를 추가하기만 함으로써 요구사항을 충족시켜나감으로써 **기존 코드의 변경으로 인한 Side-Effect 를 막는 것** 이 핵심이라고 생각합니다~!
따라서 `어떤 enum의 case가 추가되었을 때 해당 enum의 switch 구문에 추가가 발생하는 것`은 OCP를 위배하지 않는 규칙이라고 생각합니다.
다만, 바로 떠오르는 예시는 없지만 만약 `case가 추가되었을 때 기존 코드에 추가가 아닌 변경이 발생하는 것`은 OCP 를 잘 준수하지 않은 형태라고 생각합니다 🤔

---

Step2 진행까지 고생 많으셨습니다 👏👏

P1 코멘트가 있어 Request Changes 로 요청드렸지만 프로젝트 수행 기간이 지났기 때문에 해당 PR은 클로즈하고 바로 Week2 프로젝트를 진행하셔도 괜찮습니다!
하지만 이번 스텝의 핵심 내용이었던 OCP는 현재 잘 지켜졌다고 보기 어렵기 때문에 이 부분은 꼭 확인하고 넘어가실 수 있다면 좋겠습니다 🙌
(또한, 요구사항 중 `Discount 열거형에 strategy 프로퍼티를 추가합니다.` 내용이 누락된 것으로 보여요)

코멘트 내용 중 궁금한 점이 있다면 언제든 질문 부탁드립니다~!!

2024-01-28 13:53 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +// MARK: - 수정 전 코드
p4;

수정 히스토리는 커밋으로 남기고 있으니 주석을 삭제하면 어떨까요?

2024-01-28 13:53 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderView.swift
> +                    discountStrategies: [NoDiscount(), VIPDiscount(), CouponDiscount()],
p1;

`DiscountStrategy` 가 추가될 때마다 View 에서 수정이 발생하고 있기 때문에 `확장에는 열려있고 수정에는 닫혀있는` OCP 를 잘 지키고 있는 것인지 의문이 들어요 🤔
`DiscountStrategy` 의 확장에 `ParcelOrderView` 가 영향받지 않도록 작성해볼 수 있을까요?

요구사항에 주어진 힌트에 따라 `Discount` 열거형 내부에 `strategy` 프로퍼티를 추가해보는 방식을 적용해보시는 것을 추천드립니다!

2024-01-28 13:53 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +enum DiscountAmount {
p3;

enum 타입으로 선언한 이유가 무엇일까요?
case 를 사용하지 않는 enum 이라 의문이 들어 질문드립니다!

2024-01-30 02:57 UTC, Khan1201 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +enum DiscountAmount {
관련되어 있는 요소들을 묶어주기 위해서 Name Space 용도로 사용했습니다 !

2024-01-30 03:15 UTC, Khan1201 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderView.swift
> +                    discountStrategies: [NoDiscount(), VIPDiscount(), CouponDiscount()],
기존 Discount enum 내부에 [DiscountStrategy] 타입의 타입 프로퍼티(strategies)를 선언하여 ParcelOrderView에서 Discount.strategies로 사용하는 방식을 생각하였습니다.

case가 추가된다면 내부에서 바로 수정가능하므로 이렇게 생각해보았습니다 ! 
븨븨님의 의견을 들어보고 싶습니다 🤔🤔

```swift
enum Discount: Int {
    case none = 0, vip, coupon
    
    static let strategies: [DiscountStrategy] = [NoDiscount(), VIPDiscount(), CouponDiscount()]
}

// ParcelOrderView
 do {
            let parcelInformation: ParcelInformation = .init(
                user: .init(
                    address: address,
                    receiver: .init(
                        name: name,
                        mobile: mobile
                    )
                ),
                cost: try .init(
                    delivery: cost,
                    discountStrategies: Discount.strategies,
                    discountCategory: discount
                )
            )
            delegate.parcelOrderMade(parcelInformation)
            
} catch {
            print("discount에 해당되는 DiscountStrategy가 존재하지 않습니다.")
}
```

`요구사항에 주어진 힌트에 따라 Discount 열거형 내부에 strategy 프로퍼티를 추가해보는 방식을 적용해보시는 것을 추천드립니다!`

- 해당 주어진 힌트에 만족하는 코드 (step 2 요구조건 만족 코드)
- 힌트에 만족하는 코드를 보완한 코드 (step 2 요구조건 만족 코드를 보완한 코드)

의 내용을 주석으로 구분지어 작성했었는데, 커밋 히스토리로 보니 너무 지저분 한 것 같아 죄송스럽습니다 🥲
앞으로는 커밋 히스토리를 적극 활용하겠습니다 😂😂

2024-01-30 03:17 UTC, Khan1201 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +// MARK: - 수정 전 코드
수정 전 / 후를 직관적이게 볼 수 있도록 이렇게 관리 해보았는데, 히스토리가 지저분하게 쌓이는 것을 보았습니다 😅
앞으로는 수정 히스토리를 커밋으로 확인 하겠습니다 !

2024-01-30 03:21 UTC, Khan1201 commented
궁금한 내용은 코멘트에 작성 해두었습니다 !

궁금증에 대한 내용만 해결되면 되므로, 수정은 진행 안해도 될 것 같습니다.

Week2를 진행하면서, 궁금증을 해결 해보겠습니다.

감사합니다 븨븨 고생 많으셨어요 !! 👍👍

2024-01-30 13:54 UTC, YebinKim commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderView.swift
> +                    discountStrategies: [NoDiscount(), VIPDiscount(), CouponDiscount()],
ParcelOrderView 에서는 수정이 일어나지 않는다는 점이 개선되었지만,
`strategies` 는 실제로 단 하나의 Discount case 만을 필요로 함에도 모든 종류의 `DiscountStrategy` 를 필요로 하기에 불필요한 공간의 메모리를 차지하고 있어서 아쉬운 점이 있다고 생각됩니다 🤔

`strategy` 프로퍼티가 `Discount` case 에 따라 필요한 `DiscountStrategy` 를 선택적으로 알려줄 수 있다면 `DiscountStrategy` 프로토콜에서도 `DiscountStrategy` 필터링을 위한 로직을 제거할 수 있고, 필수 요구사항만을 최소한으로 가진다면 확장에도 더욱 열린 구조가 될 수 있을 것으로 보입니다!

2024-01-30 13:55 UTC, YebinKim commented
@Khan1201 
코멘트 확인 감사합니다~
그럼 이번 프로젝트는 여기에서 Close 하겠습니다 😄

다음 프로젝트 진행도 화이팅이에요!! 💪🔥

2024-02-01 09:20 UTC, YebinKim approved these changes

2024-02-01 09:20 UTC, merged