택배송장 [STEP 2] garden
yagom-academy/refectoring-parcel-invoice pull request #34
Opened 2024-02-01 12:53 UTC by gadisom

@havilog 
코멘트 주신점 수정해서 다시 PR 올리겠습니다!

2024-02-01 14:59 UTC, havilog requested changes
과제 하시느라 고생 많으셨어요 가든!
남은 기간 달려보시죠!

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +final class NoDiscount : DiscountStrategy{
```suggestion
final class NoDiscount: DiscountStrategy {
```
: 앞에는 붙여주시고, { 앞에는 띄워주세요!

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +final class NoDiscount : DiscountStrategy{
struct, class를 선언하시는 기준이 있을까요?
이 아이는 굳이 참조타입일 필요는 없을거 같아서요!

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +        self.parcelProcessor = ParcelOrderProcessor(delegate: delegate)
1. init 시점에 ParcelOrderProcessor를 파라미터로 받아서 외부에서 주입받는 Dependency Injection을 해보는 것은 어떨까요?
2. DatabaseParcelInformationPersistence를 delegate라고 표현하신 이유가 있을까요?
특별한 위임을 하고 있는것으로 보이지 않아서요!

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    let deliveryCost: DeliveryCost //
의미 없는 주석은 지우면 좋을 듯 합니다!

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    let mobile : String
```suggestion
    let address: String
    let name: String
    let mobile: String
```

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +        })
```suggestion
        delegate.save(parcelInformation: parcelInformation) { _ in
            print("저장에 성공했습니다.")
        }
```

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    var delegate : ParcelInformationPersistence
이 delegate는 변하는 값인가요?

2024-02-01 14:59 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +    init(delegate: ParcelInformationPersistence, parcelInformation: ParcelInformation? = nil) {
parcelInformation은 필요한 정보인가요?

2024-02-01 21:40 UTC, gadisom commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +final class NoDiscount : DiscountStrategy{
이 부분 고민했습니다.. 나중에 할인 기능이 생일같은 경우 자동으로 참조되면 복잡한 로직이 추가될 수 있다고 생각해서 class 로 선언했습니다.

2024-02-02 14:14 UTC, havilog commented
[f013919](https://github.com/yagom-academy/refactoring-parcel-invoice/pull/34/commits/f0139194aeebef254c6f9cd5788a82392184b191)
이렇게 오른쪽에 커밋한 내용 오른쪽에 우클릭해서 복사하시면 
커밋이 복사되는데 복사 후 conversation에 달아놓으시면 리뷰어가 확인하기 편해서
회사에서 요렇게 하시는걸 추천드려요

![image](https://github.com/yagom-academy/refactoring-parcel-invoice/assets/57659933/7bf0fe4d-7ab1-470f-88a7-cbb182c66c97)

2024-02-02 14:34 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +final class NoDiscount : DiscountStrategy{
struct에는 복잡한 로직이 들어가면 안되는걸까요? ㅎㅎ
struct와 class의 가장 큰 차이점은 값 타입인지, 참조타입인지와 그에 따른 메모리 관리라고 알고있는데요,
공식 문서를 다시 읽어보고 본인만의 확실한 선언 기준을 가져가시는게 좋을 듯 합니다!

2024-02-02 14:35 UTC, merged