택배 송장 [STEP 1] Wan
yagom-academy/refectoring-parcel-invoice pull request #36
Opened 2024-03-05 06:19 UTC by hsw1920

@zdodev 
소대 안녕하세요! 완입니다 :)
앞으로 잘 부탁드립니다!

## 미션 요구사항
1) 객체미용체조 7원칙 ‘2개 이상의 원시타입 프로퍼티를 갖는 타입 금지’
    - `ParcelInformation` 타입중 공통된 책임을 나누어 분리할 것
2) SOLID SRP, DIP 적용
    - `ParcelOrderProcessor` 타입은 여러 책임을 갖고 있음 -> SRP 위배하고 있음.
    - `DatabaseParcelInformationPersistence` 에 의존성을 가짐 -> 의존성 역전을 통한 DIP 적용

## 1번 요구사항
### 내용
기존의 `ParcelInformation`은 
`address`, `receiverName`, `receiverMobile`, `deliveryCost`, `discount`, `discountedCost`
총 6개의 저장, 연산 프로퍼티를 갖고 있었습니다.

7원칙을 위해 이를 분리하고자 `인물관련 정보` 와 `비용관련 정보` 로 분리하여
원시타입 프로퍼티를 걷어내어 `ReceiverInformation`과 `CostInformation`을 구성하였습니다.

이후 4원칙과 9원칙 및 캡슐화를 위해 접근 제어자를 사용하거나
getValue() 메서드 등을 활용하여 관련 Data의 구조체를 정의하였습니다.

### 고민이 되었던 부분
궁금한 점은 class와 struct에 대한 문제인데요. `ParcelInformation` 은 class 였다는 점입니다.
ParcelInformation이 의존하는 `ReceiverInformation`과 `CostInformation` 은 Model의 역할로 생각하여 구조체로 구현하였습니다.
저는 관습적으로 Model은 대입보다는 생성되고 난 후 불변하는 특성이 있기 때문에 이런 부분에서는 class보다 strcut가 유리하다 생각하여 구조체로 구현하였고 class로 구현되어있던 `ParcelInformation`도 struct로 변경해주었습니다.

### 조언을 얻고 싶은 부분
**이론적으로는** 값 타입과 레퍼런스 타입의 차이점은 분명 이해하고 있지만,
실제 구현 상황에서 struct와 class를 그저 관습적으로 구분하여 사용하고 있다는 느낌이 들었습니다.
좀 더 명확한 판단 기준을 세우고 싶은데 어떤 방향으로 학습을 시작해야할 지 조언을 구하고 싶습니다.

## 2번 요구사항
### 내용
`PacelOrderProcessor` 타입은 `택배 주문 처리 로직`과 `데이터베이스 주문 정보 저장`의 두 개의 책임을 갖고 있었습니다. (SRP 위반)
이를 분리하여 `DatabaseParcelInformationPersistence` 타입을 구현한 후 save 메서드를 갖는 프로토콜을 준수하도록 하고 `PacelOrderProcessor`는 프로토콜을 의존함으로써 DIP를 적용하였습니다.

같은 방식으로 `PacelOrderProcessor`의 process 메서드를 갖는 프로토콜을 구현하여 `ParcelOrderViewController`가 `PacelOrderProcessor`의 구현체가 아닌 프로토콜을 준수하도록 하였습니다.

### 조언을 얻고 싶은 부분
`PacelOrderProcessor`나 `DatabaseParcelInformationPersistence`의 경우 네이밍을 통해서 무슨 일을 하는 지 알아보기에 힘들어보였는데요,,
Service라는 접미사를 붙이고 싶었으나 뭔가 네트워크 같고.. 네이밍에 대해서는 이렇다 할 개인적인 판단 기준이 없는 것 같습니다.
혹시.. 네이밍 관련한 개인적인 팁 같은게 있으신가요?

2024-03-05 14:46 UTC, zdodev requested changes
안녕하세요. @hsw1920 ! 반갑습니다!

스텝1 구현을 빨리 진행해주셨네요!
요구사항을 잘 확인하고 개선을 잘해주셨습니다.
폴더 구조를 잘 정리해보셨네요.👍

먼저 본문의 내용에 제 생각을 답변드리면,

`struct`와 `class`의 경우 최대한 [공식문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)를 기반으로 판단하려 합니다!
`struct`와 `class`의 특성을 평소에 잘 파악해두려고 하고, 현재 기능에 어떤 타입이 더 적합한지 고민을 많이 하면서 사용해보고 있습니다.😄

네이밍의 경우 개인적으로 길어지더라도 수행하는 기능을 명확하게 표현할 수 있는 용어를 많이 사용하려고 합니다. 주로 수행하는 역할을 많이 고민해서 명명하지만, 아키텍처나 레이어 부분도 참고하고 있습니다!

다른 질문의 답변과 함께 코멘트를 달아보았습니다.
같이 의견을 나눠보면 좋을 것 같습니다!😁

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Service/ParcelProcessor.swift
> +    }
좋습니다.👍

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Service/DatabaseParcelInformationPersistence.swift
> +}
의존성 주입을 위해 프로토콜을 잘 정의해보셨네요.👍

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Service/DatabaseParcelInformationPersistence.swift
> +final class DatabaseParcelInformationPersistence: ParcelInformationPersistence {
`ParcelOrderProcessor` 타입의 역할 중 하나를 잘 분리해보셨네요.👍

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/View/ParcelOrder/ParcelOrderViewController.swift
> +    init(parcelProcessor: ParcelOrderProcessable) {
의존성 주입을 하도록 잘 변경해보셨네요.👍

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ReceiverInformation.swift
> +}
벌써 원시값에 대해서 포장을 해보셨네요.👍
다만 `Name` 타입을 보면 일반 name을 문자열로(`name: String`) 선언한 것과 큰 차이가 없어보입니다.
어떠한 이유에서 포장을 했는지 알 수 있을까요?

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ReceiverInformation.swift
> +    }
`self` 키워드가 있는 부분도 있고 없는 부분도 있는데, 사용할 때와 사용하지 않을 때의 기준이 궁금합니다!

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ParcelInformation.swift
> +struct ParcelInformation {
프로젝트 사항에는 없었지만, 본인의 생각을 잘 가지고 `struct`로 변경해보셨네요! 좋습니다.👍

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ParcelInformation.swift
> +    private let costInformation: CostInformation
대상에 대한 정보와 비용 정보를 기준으로 새로운 타입으로 잘 분리해보셨네요.👍

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ParcelInformation.swift
> +    {
메서드 시작 중괄호(`{`)를 개행한 메서드와 안한 메서드가 있는데, 어떤 기준으로 개행하여 작성하는지 궁금합니다!

2024-03-05 14:46 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ParcelInformation.swift
> +    }
다른 부분과 공통된 질문이 있습니다.
`get` 접두사를 사용하여 메서드 이름을 정의하시는 편인지 궁금합니다!
`receiverName` 이름은 어떤지도 궁금합니다!
연산 프로퍼티 대신 메서드로 정의하신 이유가 궁금합니다!

2024-03-06 06:56 UTC, hsw1920 commented
@yagom 
STEP2 PR올리려하는데 
포크된 브랜치에 푸시를 했는데 여기 PR에 바로 적용이 되어 새로 PR을 올릴 수가 없는것 같습니다.
새로운 STEP마다 브랜치를 다시 파야할까요?

2024-03-06 14:47 UTC, zdodev commented
스텝마다 새 브랜치에 작업하시는 게 더 수월하실 것 같습니다!

2024-03-08 01:53 UTC, zdodev approved these changes
안녕하세요. @hsw1920 !

Step1 코멘트를 빠르게 수정해보셨네요!

코드에 대한 호기심과 구현자의 의견, 의도가 궁금한 부분에 대해서,
달아드린 코멘트라서 대해서 무조건 수정하지 않으셔도 됩니다!
수정도 좋고, 의견을 달아주시는 것도 좋은 방법일 것 같습니다!😁

Step1 요구사항에 대해서 잘 진행해주셔서 여기서 마무리할 수 있도록 하겠습니다!

2024-03-08 01:53 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Source/Model/ParcelInformation.swift
> +    }
`getReceiverName` 메서드를 연산 프로퍼티로 변경해보셨네요!

2024-03-08 01:53 UTC, merged