택배 송장 제조기 [STEP2] jacob
yagom-academy/refectoring-parcel-invoice pull request #5
Opened 2024-01-23 14:01 UTC by wargi

@zdodev 
안녕하세요!
택배 송장 제조기 [STEP2] PR 요청드립니다~
STEP2를 진행하면서 조금씩 더 리팩토링 진행해보았습니다.

## 고민했던 점
`ParcelInformation`에서 사용하는 곳에서 접근을 편하게 하기 위해서 계산 속성을 추가했다가 삭제하였는데요.
```swift
struct ParcelInformation {
  var receiverName: PersonName {
      receiverInfomation.name
  }
      
  var receiverMobile: PhoneNumber {
      receiverInfomation.mobile
  }
}
```

`ReceiverInformation` 타입을 만든 의미가 없어지는 듯한 생각이 들어서 삭제하였는데, 
사용하는 곳에서 4원칙을 지키기 위해 상수로 한번 나누어서 사용하는게 좋을지 고민했습니다~

```swift
// as-is
nameLabel.text = "이름 : \(parcelInformation.name)"
mobileLabel.text = "전화 : \(parcelInformation.mobile)"

// to-be
let receiverInfomation = parcelInformation.receiverInfomation
nameLabel.text = "이름 : \(receiverInfomation.name)"
mobileLabel.text = "전화 : \(receiverInfomation.mobile)"
```

## 해결하지 못한 부분
`ParcelInformation`의 `Mark`한 부분을 모두 분리 혹은 구조체마다 분리해야하는지 고민되었는데요.
파일 단위로 나눌 때, 명확하기만 하다면 작은 양의 코드라도 분리하는게 맞는지 하위타입은 같이 놔두는게 맞는지기 고민됩니다..🤔

## 조언을 얻고 싶은 부분
switch 내부에서 사용하고 있는 요금 계산 로직을 분리는 하였지만,
"enum 자체를 없앨 수 없을까?🤔" 고민을 해보았는데요..
현재는 `strategies`라는 factory를 하나 만들어서 discount enum을 삭제하고,
`strategyType(String)`으로 찾는 방식으로 구현하였는데요!

```swift
class DiscountStrategyFactory {
    private static var strategies: [String: () -> DiscountStrategy] = [
        "VIP": { VIPDiscount() },
        "Coupon": { CouponDiscount() },
        "None": { NoDiscount() }
    ]

    static func createStrategy(type: String) -> DiscountStrategy {
        return strategies[type] ?? { NoDiscount() }()
    }
}
```

할인 타입이 늘어날 때마다 factory를 수정하게 되어서
2원칙에 위배되지만 `switch`를 쓰는게 가독성 이점이라도 찾을 수 있지않을까 싶기도하고 고민이 드는데,
소대는 어떻게 생각하시는지 궁금합니다~

2024-01-25 14:07 UTC, zdodev requested changes
안녕하세요. @wargi !

Step2 진행도 잘해주셨습니다👍
팩토리 패턴을 활용해서 할인 정책을 만드신 부분이 인상깊었습니다!

개인적으로 하나의 파일에 하나의 타입만을 구현하지만, 타입 간의 연관성을 생각해서 모아두거나 nested 타입으로 구현하고는 합니다. 이부분은 개인의 기준을 가지고 구현하면 좋을 것 같습니다!😁

다른 궁금증에 대해서는 코멘트와 함께 남겨보았습니다.
같이 의견 나눠보면 좋을 것 같습니다!

2024-01-25 14:07 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +struct ParcelInformation {
OCP가 지켜지도록 개선해보셨네요!👍

2024-01-25 14:07 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    var discountType: String { get }
`DiscountStrategy` 타입에 `discountType` 타입을 추가해보셨네요.
`discountType` 타입을 문자열로 정의하신 이유가 궁금합니다!

2024-01-25 14:07 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    }
프로토콜 기본 구현을 통해 `NoDiscount` 타입의 `applyDiscount` 메서드 정의를 생략해볼 수 있을꺼 같습니다.
여기에 대한 의견이 궁금합니다!

2024-01-25 14:07 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    }
할인 정책에 따라 `applyDiscount`를 잘 정의해보셨네요!👍

2024-01-25 14:07 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    ]
지금과 같은 코드 구성일 때, 할인 정책들을 미리 생성해두는 편인지 궁금합니다!

2024-01-28 05:00 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    }
넵! 처음에 extension으로 기본 구현을 해놓고 수정을 하였는데요!
NoDiscount라는 구체 타입의 내용이 기본 구현으로 가게되면 혹시 나중에
새로운 정책 타입이 생겨날 때, `applyDiscount` 함수를 추가하지 않거나 깜박하는 실수 등이 있을듯하여
수정했습니다~

2024-01-28 05:22 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    var discountType: String { get }
정책이 추가될 때 마다 `Discount`라는 `enum`타입의 `case`가 추가되는 의존성(?)을
없애고 싶어서 문자열 타입으로 추가하였습니다~!
소대는 위와 같은 상황이라면 어떻게 하셨을지 궁금합니다!

2024-01-28 05:34 UTC, wargi commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    ]
`switch`, `else`를 지양하는 쪽으로 생각하여 생성해놓았는데요..!
원래라면 `Factory` 내부에 `switch`를 이용하여 필요한 정책만 생성하는 방향으로 구현해두었을것 같습니다!

2024-01-29 13:49 UTC, zdodev commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelInformation.swift
> +    var discountType: String { get }
`Discount`의 정의를 무엇(타입)으로 할까 고민이 들었습니다!
할인이라는 것을 구별하는 요소를 어떻게 할까 생각해 보았을때, `case`가 늘어나면서 수정되는 점이 있지만 `enum`을 통한 구분이 보다 명확하면서도 휴먼에러를 줄일 수 있지 않았을까 싶었습니다!
`createStrategy(type:)` 팩터리 메서드 인자 타입이 `String` 으로 되어있어서 `type`이름의 의미가 모호할 수 있지 않을까 생각이 듭니다.
`Discount` 할인을 나타내는 포장할 수 있는 타입을 만들면 가독성 부분도 좋아질 것 같습니다!

2024-01-29 13:53 UTC, zdodev approved these changes
안녕하세요. @wargi !

Step2 진행도 잘해주셨습니다~!
본인만의 생각과 팩터리 구조에 대한 시도도 좋았습니다!

작성한 코멘트만 확인하고 넘어가면 좋을 것 같습니다! 고생하셨습니다.🎉

2024-01-29 13:54 UTC, merged