택배 송장 제조기 [STEP 1] eunduk2
yagom-academy/refectoring-parcel-invoice pull request #53
Opened 2024-04-14 04:42 UTC by EunDuk2

@havilog 
안녕하세요, 첫 리뷰 잘 부탁드립니다. pr과정에서 부족한 부분은 말씀해주시면 보완해서 진행하도록 하겠습니다!

1. STEP 1 중 7원칙 적용

- 구현 내용
address와 Name, Moblie을 Person타입으로 묶어 관리 했습니다.
강의에서 들은 것 처럼 Person안에서도 각자의 타입을 구현하여 예외처리도 할 수 있게 하였습니다.
Error 타입의 enum을 구현하여 각 프로퍼티 Init안에서 throw로 상황에 맞는 error를 던지도록 처리하였습니다.

- 궁금한 점
1. ParcelOrderView에서 아울렛 변수들의 값을 가져와 information을 init하고 있는데 이 과정에서 try를 하고 있기 때문에 catch문으로 오류에 관한 예외 처리를 해주어야 합니다. 이 오류 처리를 view에서 진행해도 되는지 궁금합니다. controller에서 해야하지 않나 싶은 생각이 들었습니다.
2. 1번에서 진행한 init과정에서 try가 여러 개 있기 때문에 catch문에서도 각자에 맞는 예외 처리를 해주어야 한다고 생각합니다. 지금 제가 구현한대로 여러 개의 catch문을 사용한 것이 바람직할까요? 하나의 catch문에서 else를 통해 여러 개의 오류 처리를 하는 것이 나을까요?
3. 각 오류에 관한 예외 처리는 alert를 띄우는 것으로 하였습니다. 지금은 임시로 ViewController에 1개의 showAlert함수만 구현해 놓았지만 앱이 커지면 많은 오류 처리에 관한 함수가 추가될 것 같습니다. 그렇다면 view에 연결된 하나의 viewController에 모든 오류 처리 함수를 추가해도 문제 없을까요? 아니면 오류 처리 함수만 모아놓는 새로운 viewController를 구현해야 할까요?

2. STEP 1 중 DIP 적용

- 구현 내용
ParcelOrderProcessor가 DatabaseParcelInformationPersistence직접 소유하고 있는 부분은 상세하게 설명해주셔서 따라가면서 어렵지 않게 구현하였습니다.
ParcelOrderViewController의 DIP구현은 위 내용과 비슷하게 구현해보았습니다.
마찬가지로 protocol을 하나 만들어 process함수를 정의하고 ParcelOrderViewController에서 delegate로 ParcelOrderProcessor를 주입하여 process사용 하였습니다.

- 궁금한 점
프로토콜 타입인 delegate변수를 정의하고 init에서 다음과 같이 의존성을 주입해주었습니다.
private var delegate: ParcelOrderProtocol
    
init() {
    self.delegate = ParcelOrderProcessor(delegate: DatabaseParcelInformationPersistence())
    ..

이 때 혼란스러운 점이 있었는데 위와 같이 ParcelOrderProcessor라는 직접적인 의존성을 주입하면 protocol을 통해 의존성 역전을 올바르게 구현한 것이 맞는지 의문이 들었습니다. (의존성 주입 과정에서 프로토콜이 아닌 ParcelOrderProcessor를 바라보게 되는게 아닌가 하는 의문)
그래서 init에서 파라미터로 의존성을 받아서 주입해줘야하나 하고 보니, ScenDelegate에서 그런 과정을 진행하는 것이 맞는지 또 다른 의문이 들었습니다.

이상입니다! 감사합니다.

2024-04-14 15:20 UTC, havilog reviewed
구현하시느라 고생 많으셨습니다!
구현 방향이 감이 잘 안오신다면 다른 분들의 피알 내용을 보고 참고하는 것도 하나의 방법이 될 수 있을것 같구요,
이해 안되시는 부분 있으시면 언제든지 디엠 주세요!

2024-04-14 15:20 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +}
Person이라는 구조체는 모델의 역할을 하고 있다고 생각하는데요, 모델은 raw한 데이터들로 구성되어야한다고 생각합니다! 
따라서 이렇게 각 객체들을 나누어주는것보다는, 하나같은 성격을 띄는 아이들끼리 묶어서 구조체로 선언해주고, validation을 하는 역할은 비지니스로직을 처리하는 곳에서 다른 객체가 해야할 것 같아요

2024-04-14 15:20 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
>  }
이 친구들은 파일을 나누면 좋을 것 같아요!

2024-04-14 15:20 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +    private var delegate: ParcelOrderProtocol
```suggestion
    private var parcelOrderProcessor: ParcelOrderProtocol
```

2024-04-14 15:20 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
>      init() {
init 시점에 ParcelOrderProcessor를 파라미터로 주입받는건 어떨까요?
이를 생성자 주입이라고 하는데요,
Dependency를 외부에서 주입받으면 해당 객체를 다른 객체로 대체하기 쉬워져서 확장성이 좋아져요!

Dependency Injection 키워드로 검색해보시면 좋을 듯 합니다!

2024-04-14 15:20 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderView.swift
> +        }
이 부분에서 고민이 많으셨던거로 보이는데요,

모델을 생성하는 것은 생각하시는 것보다는 중요도가 떨어진다고 이해해주시면 될 것 같아요.
스탭1에서는 성격이 다른 프로퍼티들을 어떻게 여러 개의 모델로 쪼갤까?를 가르치고 싶으셨던 것 같네요.

모델에 대한 검증은 모델을 가져오고 생성하는 부분(데이터베이스나 네트워크 쪽이겠죠?)에서 해줘야할 것 같고,
뷰에서는 모델을 생성하는 것보다는 모델을 받아서 뷰를 그리는데 집중해주면 될 것 같아요

그렇게 되면 ParcelOrderView는 뷰를 그리는 역할
ParcelOrderViewController는 각각의 객체를 연결하고, 알럿을 띄워주고, 뷰를 구성해주는 역할
ParcelOrderProcessor는 데이터베이스에서 어떤 모델을 어떤 방식으로 어떻게 꺼내올지
DatabaseParcelInformationPersistence는 CRUD만 담당하는 역할

이런식으로 정리될 수 있을 것 같아요!

2024-04-15 01:43 UTC, EunDuk2 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
>      init() {
ParcelOrderViewController는 SceneDelegate에서 init하고 있는데 그러면 의존성 주입을 SceneDelegate에서 진행해도 상관 없는건가요??

2024-04-15 01:46 UTC, EunDuk2 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +}
그러면 위 형태보다는 Person프로퍼티를 아래와 같이 구현하고 Controller에서 validation을 진행하는 것이 낫다는 말씀이신가요?
```
struct Person {
    private let address: String
    private var name: String
    private var mobile: String
```

2024-04-15 02:11 UTC, EunDuk2 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderView.swift
> +        }
아직 어렵지만 말씀하신대로 수정해보도록 하겠습니다!

2024-04-15 14:09 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelProcessor.swift
> +}
넵 모든 프로퍼티를 원시타입으로 가지고 있는것보다는, 비슷한 성격의 아이들을 묶거나, 
서버 혹은 디비에서 선언한 대로 구현해주면 좋을 것 같아요~

2024-04-15 14:10 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
>      init() {
넵 상위 객체에서 만들어주시면 될 것 같아요
initializer에 default value를 선언해주시는 방법도 생각해보실 수 있을 것 같구요,
더 나아가면, DI Container 개념도 나오는데, 검색해보시면 좋을 듯 합니다!

2024-04-16 08:32 UTC, EunDuk2 commented
@havilog 

말씀해주신 내용들 수정해보았습니다!
받은 데이터 검증을 위해 로직을 짜보았는데 구현할 수록 더 어렵고 이게 맞는지 의문이 드네요ㅠㅠ

피드백 부탁 드립니다!

2024-04-17 00:28 UTC, havilog reviewed
수고하셨어요! 코멘트 참고해주세요~!

2024-04-17 00:28 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/DatabaseParcelInformationPersistence.swift
> +enum personValidationError: Error {
에러 타입은 대문자로 시작해주시면 좋을거 같아요!

2024-04-17 00:28 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +    private var parcelOrderProcessor: ParcelOrderProtocol
이친구는 variable이어야할까요?

2024-04-17 00:28 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +    init(parcelOrderProcessor: ParcelOrderProtocol = ParcelOrderProcessor(parceInfoPersistence: DatabaseParcelInformationPersistence())){
이렇게 사용하면 안되는 건 아니지만,
보통은 디폴트 값울 줄때 하나의 객체만 이니셜라이즈 하는게 알아보기 쉬운거 같아요!

parcelOrderProcessor이 필요한 의존성들 또한 디폴트 값을 주는 방법도 있을거 같고,
신델에서 처리해줘도 좋을거 같아요

2024-04-17 00:28 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +    func showErrorAlert() {
어떤 타입의 어떤 타이틀, 메세지 등을 보여줄지 등을 파라미터로 받으먄 좋을거 같구,
더 나아가 알럿을 띄우는 객체를 따로 분리하는거 까지 가능할듯 합니다-!

2024-04-17 00:28 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
>          }
보통 비동기 처리에서 에러를 받으면 closure 의 리턴값으로 result를 받아서 처리하는거 같아요

아마 내부에서 비동기처리 "처럼" 구현되어있는거 같은데요,

async await로 변경되거나, closure에서 에러를 받는 방식으로 변경되어야할 거 같아요

또한 다른 에러일 경우에도 에러처리가 필요해보여요

2024-04-17 00:28 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/Person.swift
> +    }
요 친구들도 사실 요즘은 많이 안쓰는 패턴인거 같아요!

모델의 역할을 하는 친구들의 프로퍼티를 숨길 필요는 없다고 생각합니다 ㅎㅎ

2024-04-17 12:19 UTC, EunDuk2 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +    private var parcelOrderProcessor: ParcelOrderProtocol
let이 올바른 것 같습니다. 수정하였습니다!

2024-04-17 14:48 UTC, EunDuk2 commented
말씀하신 것들 수정해보았습니다!
비동기 처리에 아직 익숙치 않아서 관련해서 공부가 더 필요할 것 같습니다.
감사합니다!

2024-04-18 14:18 UTC, havilog requested changes
수고하셨습니다~!

2024-04-18 14:18 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/AlertManager.swift
> +protocol alertManager {
프로토콜의 선언은 대문자로 해주세요!

2024-04-18 14:18 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/AlertManager.swift
> +    func showOneButtonAlert(viewController: UIViewController,title:String, message: String)
```suggestion
    func showOneButtonAlert(on viewController: UIViewController, title:String, message: String)
```

2024-04-18 14:18 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/AlertManager.swift
> +class AlertManager: alertManager {
이 친구는 반드시 reference type일지 궁금합니다!
또한 class로 선언할 때에는 final을 default로 붙여주심 좋을 것 같아요

vtable, static / dynamic dispatch를 키워드로 참고해주세요

2024-04-18 14:18 UTC, havilog commented on ParcelInvoiceMaker/ParcelInvoiceMaker/ParcelOrderViewController.swift
> +                DispatchQueue.main.async {
Task와 DispatchQueue는 관리하는 주체가 달라서 이 코드는 지양해야합니다!
@MainActor나, MainActor.run 을 사용해주세요

2024-04-18 14:35 UTC, EunDuk2 commented on ParcelInvoiceMaker/ParcelInvoiceMaker/AlertManager.swift
> +class AlertManager: alertManager {
아직은 class와 struct를 어느 상황에서 적용할지 100프로 와닿지는 않아서 추가적인 학습을 진행하겠습니다!

2024-04-20 05:23 UTC, merged